name: Prepare Release
on:
  workflow_dispatch:
   
jobs:
  prepare:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Configure Git User
        run: |
          git config user.email "thiagolvlsantos@gmail.com"
          git config user.name "Thiago Santos"
      - name: Prepare repository
        run: mvn -U -B --no-transfer-progress -Prelease release:clean release:prepare
